server:
  port: 8000
spring:
  devtools:
    livereload:
      enabled: true
  datasource:
<<<<<<< HEAD
    url: jdbc:mysql://localhost:3306/rollin?serverTimezone=UTC&characterEncoding=UTF-8
=======
    url: jdbc:mysql://localhost:3306/rollin?serverTimezone=UTC&amp
    characterEncoding : UTF-8
>>>>>>> paper
    username : root
    password: 1234
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  servlet:
    multipart:
      max-file-size: 1MB
      max-request-size: 10MB
mybatis:
  config-location: classpath:config/MyBatis.xml